# Generated by Django 4.1.13 on 2025-07-05 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_wishlistgroup_alter_wishlistitem_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlistitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='wishlistitem',
            name='wishlist',
        ),
        migrations.DeleteModel(
            name='WishlistGroup',
        ),
        migrations.DeleteModel(
            name='WishlistItem',
        ),
    ]
