# Generated by Django 4.1.13 on 2025-07-05 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0007_remove_wishlistitem_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishListData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wishlist_name', models.CharField(max_length=255)),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.productdata')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlists', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
