# Generated by Django 4.1.13 on 2025-07-05 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_wishlistdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupWishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=100)),
                ('wishlistname', models.CharField(max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.productdata')),
            ],
            options={
                'unique_together': {('group', 'product', 'wishlistname')},
            },
        ),
        migrations.DeleteModel(
            name='WishListData',
        ),
    ]
