# Generated by Django 4.1.13 on 2025-07-05 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_groupwishlist_delete_wishlistdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupWishlistName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=100)),
                ('wishlistname', models.CharField(max_length=100)),
            ],
            options={
                'unique_together': {('group', 'wishlistname')},
            },
        ),
    ]
