# Generated by Django 4.1.13 on 2025-07-23 16:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0014_wishlistgroup_alter_wishlistitem_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_code',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together={('user', 'product_code')},
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='group',
        ),
        migrations.DeleteModel(
            name='WishlistGroup',
        ),
    ]
