# Generated by Django 4.1.13 on 2025-11-20 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_item_item_code_alter_wishlist_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='stocktake',
            field=models.BooleanField(default=False),
        ),
    ]
