# Generated by Django 4.1.13 on 2026-07-03 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0017_item_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=100)),
                ('item_code', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('exp_date', models.DateField(blank=True, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packing_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'packing_list',
            },
        ),
    ]
