# Generated by Django 4.1.13 on 2026-07-03 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0018_packinglist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packinglist',
            options={'managed': False},
        ),
        migrations.AddField(
            model_name='item',
            name='writeoff',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='WriteOffItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=100)),
                ('itemname', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(default=0)),
                ('expdate', models.DateField()),
                ('item_code', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('file_paths', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writeoff_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
