# Generated by Django 4.1.13 on 2026-07-03 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_packinglist_options_item_writeoff_writeoffitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterModelTable(
            name='packinglist',
            table='PackingList',
        ),
    ]
