# Generated by Django 4.1.13 on 2026-07-04 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_remove_item_name_writeoffitem_name_writeoffbatch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writeoffitem',
            name='file_paths',
        ),
    ]
