# Generated by Django 4.1.13 on 2026-07-04 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_remove_writeoffitem_file_paths'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writeoffitem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='writeoffitem',
            name='name',
        ),
        migrations.RemoveField(
            model_name='writeoffitem',
            name='user',
        ),
    ]
