# Generated by Django 4.1.13 on 2026-07-06 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_remove_writeoffitem_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdata',
            name='cost',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
