# Generated by Django 4.1.13 on 2026-07-06 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_writeoffbatch_total_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='writeoffitem',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='writeoffitem',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
    ]
