# Generated by Django 4.1.13 on 2026-07-08 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_writeoffitem_total_cost_writeoffitem_unit_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writeoffitem',
            name='total_cost',
        ),
    ]
