# Generated by Django 4.1.13 on 2026-07-09 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_remove_writeoffitem_total_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writeoffitem',
            name='expdate',
        ),
    ]
