# Generated by Django 4.1.13 on 2026-07-09 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_remove_writeoffitem_expdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
    ]
