# Generated by Django 4.1.13 on 2026-07-12 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0030_item_unit_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='WriteOffArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('batch', 'Batch'), ('item', 'Item')], max_length=20)),
                ('source_id', models.IntegerField()),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('barcode', models.CharField(blank=True, default='', max_length=100)),
                ('itemname', models.CharField(blank=True, default='', max_length=255)),
                ('quantity', models.IntegerField(default=0)),
                ('item_code', models.CharField(blank=True, default='', max_length=100)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14)),
                ('file_paths', models.TextField(blank=True, default='')),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='writeoff_archives', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'writeoff_archive',
                'ordering': ['-deleted_at'],
            },
        ),
    ]
