# Generated by Django 4.1.13 on 2026-08-16 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_writeoffarchive'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='special',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='special_key',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='writeoffitem',
            name='special',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='writeoffitem',
            name='special_key',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
