# Generated by Django 4.1.13 on 2026-08-16 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_item_special_item_special_key_writeoffitem_special_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='special_key',
        ),
        migrations.RemoveField(
            model_name='writeoffitem',
            name='special_key',
        ),
    ]
