# Generated by Django 4.1.13 on 2026-08-16 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_remove_item_special_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='writeoffarchive',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
