# Generated by Django 4.1.13 on 2026-08-16 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_writeoffarchive_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='writeoffarchive',
            name='special',
            field=models.BooleanField(default=False),
        ),
    ]
