# Generated by Django 4.1.13 on 2026-08-17 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_productdata_unit_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdata',
            name='item_code',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
