# Generated by Django 4.1.13 on 2026-08-17 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_alter_productdata_item_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdata',
            name='unit_cost',
        ),
        migrations.AlterField(
            model_name='productdata',
            name='item_code',
            field=models.CharField(max_length=50),
        ),
    ]
