# Generated by Django 4.1.13 on 2026-08-17 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_remove_productdata_unit_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdata',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
    ]
