# Generated by Django 4.1.13 on 2026-08-20 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_productdata_unit_cost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PackingList',
        ),
    ]
