# Generated by Django 4.1.13 on 2026-08-20 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_delete_packinglist'),
    ]

    operations = [
        migrations.AddField(
            model_name='writeoffarchive',
            name='is_refund_archive',
            field=models.BooleanField(default=False),
        ),
    ]
