# Generated by Django 4.1.13 on 2026-08-20 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_writeoffarchive_is_refund_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='writeoffbatch',
            name='is_refund',
            field=models.BooleanField(default=False),
        ),
    ]
